nama=input("Nama                   : ")
nim=input("NIM                    : ")
kelas=input("Kelas Parallel         : ")
ttl=input("Tempat/Tanggal Lahir   : ")
alamat=input("Alamat                 : ")
hobby=input("Hobby                  : ")
hp=input("No. HP                 : ")
